# Generated by Django 3.2.5 on 2021-09-25 14:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20210814_2044'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('active_books', django.db.models.manager.Manager()),
            ],
        ),
    ]
